// <auto-generated />
using System;
using EventsDemoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventsDemoAPI.Data.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20230808121746_events")]
    partial class events
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("EventsDemoAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimezoneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimezoneId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventsDemoAPI.Models.MTimezone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("abbr")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("isdst")
                        .HasColumnType("INTEGER");

                    b.Property<float>("offset")
                        .HasColumnType("REAL");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("MTimezones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            abbr = "DST",
                            isdst = false,
                            offset = -12f,
                            text = "(UTC-12:00) International Date Line West",
                            value = "Dateline Standard Time"
                        },
                        new
                        {
                            Id = 2,
                            abbr = "U",
                            isdst = false,
                            offset = -11f,
                            text = "(UTC-11:00) Coordinated Universal Time-11",
                            value = "UTC-11"
                        },
                        new
                        {
                            Id = 3,
                            abbr = "HST",
                            isdst = false,
                            offset = -10f,
                            text = "(UTC-10:00) Hawaii",
                            value = "Hawaiian Standard Time"
                        },
                        new
                        {
                            Id = 4,
                            abbr = "AKDT",
                            isdst = true,
                            offset = -8f,
                            text = "(UTC-09:00) Alaska",
                            value = "Alaskan Standard Time"
                        },
                        new
                        {
                            Id = 5,
                            abbr = "PDT",
                            isdst = true,
                            offset = -7f,
                            text = "(UTC-08:00) Baja California",
                            value = "Pacific Standard Time (Mexico)"
                        },
                        new
                        {
                            Id = 6,
                            abbr = "PDT",
                            isdst = true,
                            offset = -7f,
                            text = "(UTC-07:00) Pacific Daylight Time (US & Canada)",
                            value = "Pacific Daylight Time"
                        },
                        new
                        {
                            Id = 7,
                            abbr = "PST",
                            isdst = false,
                            offset = -8f,
                            text = "(UTC-08:00) Pacific Standard Time (US & Canada)",
                            value = "Pacific Standard Time"
                        },
                        new
                        {
                            Id = 8,
                            abbr = "UMST",
                            isdst = false,
                            offset = -7f,
                            text = "(UTC-07:00) Arizona",
                            value = "US Mountain Standard Time"
                        },
                        new
                        {
                            Id = 9,
                            abbr = "MDT",
                            isdst = true,
                            offset = -6f,
                            text = "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
                            value = "Mountain Standard Time (Mexico)"
                        },
                        new
                        {
                            Id = 10,
                            abbr = "MDT",
                            isdst = true,
                            offset = -6f,
                            text = "(UTC-07:00) Mountain Time (US & Canada)",
                            value = "Mountain Standard Time"
                        },
                        new
                        {
                            Id = 11,
                            abbr = "CAST",
                            isdst = false,
                            offset = -6f,
                            text = "(UTC-06:00) Central America",
                            value = "Central America Standard Time"
                        },
                        new
                        {
                            Id = 12,
                            abbr = "CDT",
                            isdst = true,
                            offset = -5f,
                            text = "(UTC-06:00) Central Time (US & Canada)",
                            value = "Central Standard Time"
                        },
                        new
                        {
                            Id = 13,
                            abbr = "CDT",
                            isdst = true,
                            offset = -5f,
                            text = "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
                            value = "Central Standard Time (Mexico)"
                        },
                        new
                        {
                            Id = 14,
                            abbr = "CCST",
                            isdst = false,
                            offset = -6f,
                            text = "(UTC-06:00) Saskatchewan",
                            value = "Canada Central Standard Time"
                        },
                        new
                        {
                            Id = 15,
                            abbr = "SPST",
                            isdst = false,
                            offset = -5f,
                            text = "(UTC-05:00) Bogota, Lima, Quito",
                            value = "SA Pacific Standard Time"
                        },
                        new
                        {
                            Id = 16,
                            abbr = "EST",
                            isdst = false,
                            offset = -5f,
                            text = "(UTC-05:00) Eastern Time (US & Canada)",
                            value = "Eastern Standard Time"
                        },
                        new
                        {
                            Id = 17,
                            abbr = "EDT",
                            isdst = true,
                            offset = -4f,
                            text = "(UTC-04:00) Eastern Daylight Time (US & Canada)",
                            value = "Eastern Daylight Time"
                        },
                        new
                        {
                            Id = 18,
                            abbr = "UEDT",
                            isdst = false,
                            offset = -5f,
                            text = "(UTC-05:00) Indiana (East)",
                            value = "US Eastern Standard Time"
                        },
                        new
                        {
                            Id = 19,
                            abbr = "VST",
                            isdst = false,
                            offset = -4.5f,
                            text = "(UTC-04:30) Caracas",
                            value = "Venezuela Standard Time"
                        },
                        new
                        {
                            Id = 20,
                            abbr = "PYT",
                            isdst = false,
                            offset = -4f,
                            text = "(UTC-04:00) Asuncion",
                            value = "Paraguay Standard Time"
                        },
                        new
                        {
                            Id = 21,
                            abbr = "ADT",
                            isdst = true,
                            offset = -3f,
                            text = "(UTC-04:00) Atlantic Time (Canada)",
                            value = "Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 22,
                            abbr = "CBST",
                            isdst = false,
                            offset = -4f,
                            text = "(UTC-04:00) Cuiaba",
                            value = "Central Brazilian Standard Time"
                        },
                        new
                        {
                            Id = 23,
                            abbr = "SWST",
                            isdst = false,
                            offset = -4f,
                            text = "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
                            value = "SA Western Standard Time"
                        },
                        new
                        {
                            Id = 24,
                            abbr = "PSST",
                            isdst = false,
                            offset = -4f,
                            text = "(UTC-04:00) Santiago",
                            value = "Pacific SA Standard Time"
                        },
                        new
                        {
                            Id = 25,
                            abbr = "NDT",
                            isdst = true,
                            offset = -2.5f,
                            text = "(UTC-03:30) Newfoundland",
                            value = "Newfoundland Standard Time"
                        },
                        new
                        {
                            Id = 26,
                            abbr = "ESAST",
                            isdst = false,
                            offset = -3f,
                            text = "(UTC-03:00) Brasilia",
                            value = "E. South America Standard Time"
                        },
                        new
                        {
                            Id = 27,
                            abbr = "AST",
                            isdst = false,
                            offset = -3f,
                            text = "(UTC-03:00) Buenos Aires",
                            value = "Argentina Standard Time"
                        },
                        new
                        {
                            Id = 28,
                            abbr = "SEST",
                            isdst = false,
                            offset = -3f,
                            text = "(UTC-03:00) Cayenne, Fortaleza",
                            value = "SA Eastern Standard Time"
                        },
                        new
                        {
                            Id = 29,
                            abbr = "GDT",
                            isdst = true,
                            offset = -3f,
                            text = "(UTC-03:00) Greenland",
                            value = "Greenland Standard Time"
                        },
                        new
                        {
                            Id = 30,
                            abbr = "MST",
                            isdst = false,
                            offset = -3f,
                            text = "(UTC-03:00) Montevideo",
                            value = "Montevideo Standard Time"
                        },
                        new
                        {
                            Id = 31,
                            abbr = "BST",
                            isdst = false,
                            offset = -3f,
                            text = "(UTC-03:00) Salvador",
                            value = "Bahia Standard Time"
                        },
                        new
                        {
                            Id = 32,
                            abbr = "U",
                            isdst = false,
                            offset = -2f,
                            text = "(UTC-02:00) Coordinated Universal Time-02",
                            value = "UTC-02"
                        },
                        new
                        {
                            Id = 33,
                            abbr = "MDT",
                            isdst = true,
                            offset = -1f,
                            text = "(UTC-02:00) Mid-Atlantic - Old",
                            value = "Mid-Atlantic Standard Time"
                        },
                        new
                        {
                            Id = 34,
                            abbr = "ADT",
                            isdst = true,
                            offset = 0f,
                            text = "(UTC-01:00) Azores",
                            value = "Azores Standard Time"
                        },
                        new
                        {
                            Id = 35,
                            abbr = "CVST",
                            isdst = false,
                            offset = -1f,
                            text = "(UTC-01:00) Cape Verde Is.",
                            value = "Cape Verde Standard Time"
                        },
                        new
                        {
                            Id = 36,
                            abbr = "MDT",
                            isdst = true,
                            offset = 1f,
                            text = "(UTC) Casablanca",
                            value = "Morocco Standard Time"
                        },
                        new
                        {
                            Id = 37,
                            abbr = "UTC",
                            isdst = false,
                            offset = 0f,
                            text = "(UTC) Coordinated Universal Time",
                            value = "UTC"
                        },
                        new
                        {
                            Id = 38,
                            abbr = "GMT",
                            isdst = false,
                            offset = 0f,
                            text = "(UTC) Edinburgh, London",
                            value = "GMT Standard Time"
                        },
                        new
                        {
                            Id = 39,
                            abbr = "BST",
                            isdst = true,
                            offset = 1f,
                            text = "(UTC+01:00) Edinburgh, London",
                            value = "British Summer Time"
                        },
                        new
                        {
                            Id = 40,
                            abbr = "GDT",
                            isdst = true,
                            offset = 1f,
                            text = "(UTC) Dublin, Lisbon",
                            value = "GMT Standard Time"
                        },
                        new
                        {
                            Id = 41,
                            abbr = "GST",
                            isdst = false,
                            offset = 0f,
                            text = "(UTC) Monrovia, Reykjavik",
                            value = "Greenwich Standard Time"
                        },
                        new
                        {
                            Id = 42,
                            abbr = "WEDT",
                            isdst = true,
                            offset = 2f,
                            text = "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
                            value = "W. Europe Standard Time"
                        },
                        new
                        {
                            Id = 43,
                            abbr = "CEDT",
                            isdst = true,
                            offset = 2f,
                            text = "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
                            value = "Central Europe Standard Time"
                        },
                        new
                        {
                            Id = 44,
                            abbr = "RDT",
                            isdst = true,
                            offset = 2f,
                            text = "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
                            value = "Romance Standard Time"
                        },
                        new
                        {
                            Id = 45,
                            abbr = "CEDT",
                            isdst = true,
                            offset = 2f,
                            text = "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
                            value = "Central European Standard Time"
                        },
                        new
                        {
                            Id = 46,
                            abbr = "WCAST",
                            isdst = false,
                            offset = 1f,
                            text = "(UTC+01:00) West Central Africa",
                            value = "W. Central Africa Standard Time"
                        },
                        new
                        {
                            Id = 47,
                            abbr = "NST",
                            isdst = false,
                            offset = 1f,
                            text = "(UTC+01:00) Windhoek",
                            value = "Namibia Standard Time"
                        },
                        new
                        {
                            Id = 48,
                            abbr = "GDT",
                            isdst = true,
                            offset = 3f,
                            text = "(UTC+02:00) Athens, Bucharest",
                            value = "GTB Standard Time"
                        },
                        new
                        {
                            Id = 49,
                            abbr = "MEDT",
                            isdst = true,
                            offset = 3f,
                            text = "(UTC+02:00) Beirut",
                            value = "Middle East Standard Time"
                        },
                        new
                        {
                            Id = 50,
                            abbr = "EST",
                            isdst = false,
                            offset = 2f,
                            text = "(UTC+02:00) Cairo",
                            value = "Egypt Standard Time"
                        },
                        new
                        {
                            Id = 51,
                            abbr = "SDT",
                            isdst = true,
                            offset = 3f,
                            text = "(UTC+02:00) Damascus",
                            value = "Syria Standard Time"
                        },
                        new
                        {
                            Id = 52,
                            abbr = "EEDT",
                            isdst = true,
                            offset = 3f,
                            text = "(UTC+02:00) E. Europe",
                            value = "E. Europe Standard Time"
                        },
                        new
                        {
                            Id = 53,
                            abbr = "SAST",
                            isdst = false,
                            offset = 2f,
                            text = "(UTC+02:00) Harare, Pretoria",
                            value = "South Africa Standard Time"
                        },
                        new
                        {
                            Id = 54,
                            abbr = "FDT",
                            isdst = true,
                            offset = 3f,
                            text = "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
                            value = "FLE Standard Time"
                        },
                        new
                        {
                            Id = 55,
                            abbr = "TDT",
                            isdst = false,
                            offset = 3f,
                            text = "(UTC+03:00) Istanbul",
                            value = "Turkey Standard Time"
                        },
                        new
                        {
                            Id = 56,
                            abbr = "JDT",
                            isdst = true,
                            offset = 3f,
                            text = "(UTC+02:00) Jerusalem",
                            value = "Israel Standard Time"
                        },
                        new
                        {
                            Id = 57,
                            abbr = "LST",
                            isdst = false,
                            offset = 2f,
                            text = "(UTC+02:00) Tripoli",
                            value = "Libya Standard Time"
                        },
                        new
                        {
                            Id = 58,
                            abbr = "JST",
                            isdst = false,
                            offset = 3f,
                            text = "(UTC+03:00) Amman",
                            value = "Jordan Standard Time"
                        },
                        new
                        {
                            Id = 59,
                            abbr = "AST",
                            isdst = false,
                            offset = 3f,
                            text = "(UTC+03:00) Baghdad",
                            value = "Arabic Standard Time"
                        },
                        new
                        {
                            Id = 60,
                            abbr = "KST",
                            isdst = false,
                            offset = 3f,
                            text = "(UTC+02:00) Kaliningrad",
                            value = "Kaliningrad Standard Time"
                        },
                        new
                        {
                            Id = 61,
                            abbr = "AST",
                            isdst = false,
                            offset = 3f,
                            text = "(UTC+03:00) Kuwait, Riyadh",
                            value = "Arab Standard Time"
                        },
                        new
                        {
                            Id = 62,
                            abbr = "EAST",
                            isdst = false,
                            offset = 3f,
                            text = "(UTC+03:00) Nairobi",
                            value = "E. Africa Standard Time"
                        },
                        new
                        {
                            Id = 63,
                            abbr = "MSK",
                            isdst = false,
                            offset = 3f,
                            text = "(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk",
                            value = "Moscow Standard Time"
                        },
                        new
                        {
                            Id = 64,
                            abbr = "SAMT",
                            isdst = false,
                            offset = 4f,
                            text = "(UTC+04:00) Samara, Ulyanovsk, Saratov",
                            value = "Samara Time"
                        },
                        new
                        {
                            Id = 65,
                            abbr = "IDT",
                            isdst = true,
                            offset = 4.5f,
                            text = "(UTC+03:30) Tehran",
                            value = "Iran Standard Time"
                        },
                        new
                        {
                            Id = 66,
                            abbr = "AST",
                            isdst = false,
                            offset = 4f,
                            text = "(UTC+04:00) Abu Dhabi, Muscat",
                            value = "Arabian Standard Time"
                        },
                        new
                        {
                            Id = 67,
                            abbr = "ADT",
                            isdst = true,
                            offset = 5f,
                            text = "(UTC+04:00) Baku",
                            value = "Azerbaijan Standard Time"
                        },
                        new
                        {
                            Id = 68,
                            abbr = "MST",
                            isdst = false,
                            offset = 4f,
                            text = "(UTC+04:00) Port Louis",
                            value = "Mauritius Standard Time"
                        },
                        new
                        {
                            Id = 69,
                            abbr = "GET",
                            isdst = false,
                            offset = 4f,
                            text = "(UTC+04:00) Tbilisi",
                            value = "Georgian Standard Time"
                        },
                        new
                        {
                            Id = 70,
                            abbr = "CST",
                            isdst = false,
                            offset = 4f,
                            text = "(UTC+04:00) Yerevan",
                            value = "Caucasus Standard Time"
                        },
                        new
                        {
                            Id = 71,
                            abbr = "AST",
                            isdst = false,
                            offset = 4.5f,
                            text = "(UTC+04:30) Kabul",
                            value = "Afghanistan Standard Time"
                        },
                        new
                        {
                            Id = 72,
                            abbr = "WAST",
                            isdst = false,
                            offset = 5f,
                            text = "(UTC+05:00) Ashgabat, Tashkent",
                            value = "West Asia Standard Time"
                        },
                        new
                        {
                            Id = 73,
                            abbr = "YEKT",
                            isdst = false,
                            offset = 5f,
                            text = "(UTC+05:00) Yekaterinburg",
                            value = "Yekaterinburg Time"
                        },
                        new
                        {
                            Id = 74,
                            abbr = "PKT",
                            isdst = false,
                            offset = 5f,
                            text = "(UTC+05:00) Islamabad, Karachi",
                            value = "Pakistan Standard Time"
                        },
                        new
                        {
                            Id = 75,
                            abbr = "IST",
                            isdst = false,
                            offset = 5.5f,
                            text = "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
                            value = "India Standard Time"
                        },
                        new
                        {
                            Id = 76,
                            abbr = "SLST",
                            isdst = false,
                            offset = 5.5f,
                            text = "(UTC+05:30) Sri Jayawardenepura",
                            value = "Sri Lanka Standard Time"
                        },
                        new
                        {
                            Id = 77,
                            abbr = "NST",
                            isdst = false,
                            offset = 5.75f,
                            text = "(UTC+05:45) Kathmandu",
                            value = "Nepal Standard Time"
                        },
                        new
                        {
                            Id = 78,
                            abbr = "CAST",
                            isdst = false,
                            offset = 6f,
                            text = "(UTC+06:00) Nur-Sultan (Astana)",
                            value = "Central Asia Standard Time"
                        },
                        new
                        {
                            Id = 79,
                            abbr = "BST",
                            isdst = false,
                            offset = 6f,
                            text = "(UTC+06:00) Dhaka",
                            value = "Bangladesh Standard Time"
                        },
                        new
                        {
                            Id = 80,
                            abbr = "MST",
                            isdst = false,
                            offset = 6.5f,
                            text = "(UTC+06:30) Yangon (Rangoon)",
                            value = "Myanmar Standard Time"
                        },
                        new
                        {
                            Id = 81,
                            abbr = "SAST",
                            isdst = false,
                            offset = 7f,
                            text = "(UTC+07:00) Bangkok, Hanoi, Jakarta",
                            value = "SE Asia Standard Time"
                        },
                        new
                        {
                            Id = 82,
                            abbr = "NCAST",
                            isdst = false,
                            offset = 7f,
                            text = "(UTC+07:00) Novosibirsk",
                            value = "N. Central Asia Standard Time"
                        },
                        new
                        {
                            Id = 83,
                            abbr = "CST",
                            isdst = false,
                            offset = 8f,
                            text = "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
                            value = "China Standard Time"
                        },
                        new
                        {
                            Id = 84,
                            abbr = "NAST",
                            isdst = false,
                            offset = 8f,
                            text = "(UTC+08:00) Krasnoyarsk",
                            value = "North Asia Standard Time"
                        },
                        new
                        {
                            Id = 85,
                            abbr = "MPST",
                            isdst = false,
                            offset = 8f,
                            text = "(UTC+08:00) Kuala Lumpur, Singapore",
                            value = "Singapore Standard Time"
                        },
                        new
                        {
                            Id = 86,
                            abbr = "WAST",
                            isdst = false,
                            offset = 8f,
                            text = "(UTC+08:00) Perth",
                            value = "W. Australia Standard Time"
                        },
                        new
                        {
                            Id = 87,
                            abbr = "TST",
                            isdst = false,
                            offset = 8f,
                            text = "(UTC+08:00) Taipei",
                            value = "Taipei Standard Time"
                        },
                        new
                        {
                            Id = 88,
                            abbr = "UST",
                            isdst = false,
                            offset = 8f,
                            text = "(UTC+08:00) Ulaanbaatar",
                            value = "Ulaanbaatar Standard Time"
                        },
                        new
                        {
                            Id = 89,
                            abbr = "NAEST",
                            isdst = false,
                            offset = 8f,
                            text = "(UTC+08:00) Irkutsk",
                            value = "North Asia East Standard Time"
                        },
                        new
                        {
                            Id = 90,
                            abbr = "JST",
                            isdst = false,
                            offset = 9f,
                            text = "(UTC+09:00) Osaka, Sapporo, Tokyo",
                            value = "Japan Standard Time"
                        },
                        new
                        {
                            Id = 91,
                            abbr = "KST",
                            isdst = false,
                            offset = 9f,
                            text = "(UTC+09:00) Seoul",
                            value = "Korea Standard Time"
                        },
                        new
                        {
                            Id = 92,
                            abbr = "CAST",
                            isdst = false,
                            offset = 9.5f,
                            text = "(UTC+09:30) Adelaide",
                            value = "Cen. Australia Standard Time"
                        },
                        new
                        {
                            Id = 93,
                            abbr = "ACST",
                            isdst = false,
                            offset = 9.5f,
                            text = "(UTC+09:30) Darwin",
                            value = "AUS Central Standard Time"
                        },
                        new
                        {
                            Id = 94,
                            abbr = "EAST",
                            isdst = false,
                            offset = 10f,
                            text = "(UTC+10:00) Brisbane",
                            value = "E. Australia Standard Time"
                        },
                        new
                        {
                            Id = 95,
                            abbr = "AEST",
                            isdst = false,
                            offset = 10f,
                            text = "(UTC+10:00) Canberra, Melbourne, Sydney",
                            value = "AUS Eastern Standard Time"
                        },
                        new
                        {
                            Id = 96,
                            abbr = "WPST",
                            isdst = false,
                            offset = 10f,
                            text = "(UTC+10:00) Guam, Port Moresby",
                            value = "West Pacific Standard Time"
                        },
                        new
                        {
                            Id = 97,
                            abbr = "TST",
                            isdst = false,
                            offset = 10f,
                            text = "(UTC+10:00) Hobart",
                            value = "Tasmania Standard Time"
                        },
                        new
                        {
                            Id = 98,
                            abbr = "YST",
                            isdst = false,
                            offset = 9f,
                            text = "(UTC+09:00) Yakutsk",
                            value = "Yakutsk Standard Time"
                        },
                        new
                        {
                            Id = 99,
                            abbr = "CPST",
                            isdst = false,
                            offset = 11f,
                            text = "(UTC+11:00) Solomon Is., New Caledonia",
                            value = "Central Pacific Standard Time"
                        },
                        new
                        {
                            Id = 100,
                            abbr = "VST",
                            isdst = false,
                            offset = 11f,
                            text = "(UTC+11:00) Vladivostok",
                            value = "Vladivostok Standard Time"
                        },
                        new
                        {
                            Id = 101,
                            abbr = "NZST",
                            isdst = false,
                            offset = 12f,
                            text = "(UTC+12:00) Auckland, Wellington",
                            value = "New Zealand Standard Time"
                        },
                        new
                        {
                            Id = 102,
                            abbr = "U",
                            isdst = false,
                            offset = 12f,
                            text = "(UTC+12:00) Coordinated Universal Time+12",
                            value = "UTC+12"
                        },
                        new
                        {
                            Id = 103,
                            abbr = "FST",
                            isdst = false,
                            offset = 12f,
                            text = "(UTC+12:00) Fiji",
                            value = "Fiji Standard Time"
                        },
                        new
                        {
                            Id = 104,
                            abbr = "MST",
                            isdst = false,
                            offset = 12f,
                            text = "(UTC+12:00) Magadan",
                            value = "Magadan Standard Time"
                        },
                        new
                        {
                            Id = 105,
                            abbr = "KDT",
                            isdst = true,
                            offset = 13f,
                            text = "(UTC+12:00) Petropavlovsk-Kamchatsky - Old",
                            value = "Kamchatka Standard Time"
                        },
                        new
                        {
                            Id = 106,
                            abbr = "TST",
                            isdst = false,
                            offset = 13f,
                            text = "(UTC+13:00) Nuku'alofa",
                            value = "Tonga Standard Time"
                        },
                        new
                        {
                            Id = 107,
                            abbr = "SST",
                            isdst = false,
                            offset = 13f,
                            text = "(UTC+13:00) Samoa",
                            value = "Samoa Standard Time"
                        });
                });

            modelBuilder.Entity("EventsDemoAPI.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("EventsDemoAPI.Models.Event", b =>
                {
                    b.HasOne("EventsDemoAPI.Models.MTimezone", "Timezone")
                        .WithMany()
                        .HasForeignKey("TimezoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Timezone");
                });

            modelBuilder.Entity("EventsDemoAPI.Models.Participant", b =>
                {
                    b.HasOne("EventsDemoAPI.Models.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventsDemoAPI.Models.Event", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
